spring:
  application:
    name: BackendProject
  data:
    mongodb:
      uri: mongodb+srv://s0990006:ejomjca;iu;pmasw@cluster0.enbbj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: test
